use crate::encrypt::{encrypt, KEY_LEN};
use crate::error::Result;
use crate::schema::SecretsToml;
use serde::Serialize;
use std::collections::BTreeMap;

const CODEGEN_VERSION: &str = env!("CARGO_PKG_VERSION");

/// appsettings.json 的根結構
#[derive(Serialize)]
pub struct AppSettings {
    #[serde(rename = "Hardvault")]
    pub hardvault: HardvaultManifest,
}

#[derive(Serialize)]
pub struct HardvaultManifest {
    #[serde(rename = "Secrets")]
    pub secrets: Vec<String>,
    #[serde(rename = "Config")]
    pub config: Vec<String>,
}

pub fn build_appsettings(toml: &SecretsToml) -> AppSettings {
    AppSettings {
        hardvault: HardvaultManifest {
            secrets: toml.secrets.keys().cloned().collect(),
            config: toml.config.keys().cloned().collect(),
        },
    }
}

/// 產生 GeneratedSecrets.cs 的內容
pub fn build_cs(toml: &SecretsToml, key: &[u8; KEY_LEN], namespace: &str) -> Result<String> {
    // 用 BTreeMap 保證 KEY 順序穩定（雖然 toml 內也是 BTreeMap，這裡確保合併後也穩定）
    let mut entries: BTreeMap<&str, (bool, Vec<u8>)> = BTreeMap::new();

    for (k, v) in &toml.secrets {
        let blob = encrypt(key, v.as_bytes())?;
        entries.insert(k.as_str(), (true, blob));
    }
    for (k, v) in &toml.config {
        entries.insert(k.as_str(), (false, v.as_bytes().to_vec()));
    }

    let mut out = String::new();
    out.push_str(&format!(
        "// <auto-generated by hardvault {CODEGEN_VERSION}>\n"
    ));
    out.push_str("// 不要手動編輯。重新產生：hardvault build\n");
    out.push_str("// 此檔包含密文與明文設定，**不要** commit 進 Git。\n");
    out.push_str("using System.Collections.Generic;\n\n");
    out.push_str(&format!("namespace {namespace};\n\n"));
    out.push_str("internal static class GeneratedSecrets\n");
    out.push_str("{\n");
    out.push_str("    internal readonly record struct Entry(bool Encrypted, byte[] Data);\n\n");
    out.push_str("    internal static readonly IReadOnlyDictionary<string, Entry> Entries =\n");
    out.push_str("        new Dictionary<string, Entry>\n");
    out.push_str("        {\n");

    for (k, (encrypted, data)) in &entries {
        let cs_bool = if *encrypted { "true" } else { "false" };
        out.push_str(&format!(
            "            [\"{k}\"] = new({cs_bool}, {}),\n",
            format_byte_array(data)
        ));
    }

    out.push_str("        };\n");
    out.push_str("}\n");
    Ok(out)
}

/// 將 byte 序列格式化為 C# `new byte[] { 0xab, 0xcd, ... }`
fn format_byte_array(bytes: &[u8]) -> String {
    if bytes.is_empty() {
        return "System.Array.Empty<byte>()".into();
    }
    let mut s = String::with_capacity(bytes.len() * 6 + 16);
    s.push_str("new byte[] { ");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("0x{b:02x}"));
    }
    s.push_str(" }");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn format_empty_bytes() {
        assert_eq!(format_byte_array(&[]), "System.Array.Empty<byte>()");
    }

    #[test]
    fn format_single_byte() {
        assert_eq!(format_byte_array(&[0xab]), "new byte[] { 0xab }");
    }

    #[test]
    fn format_multiple_bytes() {
        assert_eq!(
            format_byte_array(&[0x01, 0x02, 0xff]),
            "new byte[] { 0x01, 0x02, 0xff }"
        );
    }

    #[test]
    fn cs_contains_namespace_and_keys() {
        let toml_src = r#"
[secrets]
TOKEN = "x"

[config]
SIZE = "10"
"#;
        let toml = SecretsToml::parse(toml_src).unwrap();
        let key = [0u8; KEY_LEN];
        let cs = build_cs(&toml, &key, "Hardvault.Security").unwrap();
        assert!(cs.contains("namespace Hardvault.Security;"));
        assert!(cs.contains(r#"["TOKEN"] = new(true, new byte[]"#));
        // SIZE 是明文 "10" → UTF-8 bytes 0x31, 0x30
        assert!(
            cs.contains(r#"["SIZE"] = new(false, new byte[] { 0x31, 0x30 })"#),
            "cs:\n{cs}"
        );
    }

    #[test]
    fn cs_entries_sorted() {
        let toml_src = r#"
[secrets]
ZEBRA = "z"
ALPHA = "a"

[config]
MIKE = "m"
"#;
        let toml = SecretsToml::parse(toml_src).unwrap();
        let key = [0u8; KEY_LEN];
        let cs = build_cs(&toml, &key, "X").unwrap();

        let pos_alpha = cs.find(r#"["ALPHA"]"#).unwrap();
        let pos_mike = cs.find(r#"["MIKE"]"#).unwrap();
        let pos_zebra = cs.find(r#"["ZEBRA"]"#).unwrap();
        assert!(pos_alpha < pos_mike);
        assert!(pos_mike < pos_zebra);
    }

    #[test]
    fn appsettings_layout() {
        let toml_src = r#"
[secrets]
A = "1"

[config]
B = "2"
"#;
        let toml = SecretsToml::parse(toml_src).unwrap();
        let app = build_appsettings(&toml);
        let json = serde_json::to_string(&app).unwrap();
        assert!(json.contains(r#""Hardvault""#));
        assert!(json.contains(r#""Secrets":["A"]"#));
        assert!(json.contains(r#""Config":["B"]"#));
    }

    #[test]
    fn appsettings_empty_sections_ok() {
        let toml_src = r#"
[secrets]
ONLY = "1"
"#;
        let toml = SecretsToml::parse(toml_src).unwrap();
        let app = build_appsettings(&toml);
        let json = serde_json::to_string(&app).unwrap();
        assert!(json.contains(r#""Secrets":["ONLY"]"#));
        assert!(json.contains(r#""Config":[]"#));
    }
}
